- type: guideEntry
  id: Security
  name: guide-entry-security
  text: "/ServerInfo/Guidebook/Security/Security.xml"
  children:
  - Forensics
  - Defusal
  - CriminalRecords
  - SpaceLaw 
  - CrimeList 
  - ResItem
  - ResGear 
  - ControlSub 

- type: guideEntry
  id: Forensics
  name: guide-entry-forensics
  text: "/ServerInfo/Guidebook/Security/Forensics.xml"

- type: guideEntry
  id: Defusal
  name: guide-entry-defusal
  text: "/ServerInfo/Guidebook/Security/Defusal.xml"

- type: guideEntry
  id: CriminalRecords
  name: guide-entry-criminal-records
  text: "/ServerInfo/Guidebook/Security/CriminalRecords.xml"

- type: guideEntry
  id: SpaceLaw
  name: SpaceLaw
  text: "/ServerInfo/Guidebook/Security/SpaceLaw.xml"

- type: guideEntry
  id: ListaCrimes
  name: guide-entry-crimelist
  text: "/ServerInfo/Guidebook/Security/SLCrimeList.xml"

- type: guideEntry
  id: Items
  name: guide-entry-restrictedweapons
  text: "/ServerInfo/Guidebook/Security/SLRestrictedWeapons.xml"

- type: guideEntry
  id: Equipamentos
  name: guide-entry-restrictedgear
  text: "/ServerInfo/Guidebook/Security/SLRestrictedGear.xml"

- type: guideEntry
  id: Substancias
  name: guide-entry-controlledsubstances
  text: "/ServerInfo/Guidebook/Security/SLControlledSubstances.xml"